apiVersion: apps/v1
kind: Deployment
metadata:
  name: beekeeper-api
spec:
  template:
    spec:
      containers:
      - name: beekeeper-api
        volumeMounts:
        - $patch: delete
          name: beekeeper-test-nodes
          mountPath: /usr/lib/waggle/test-nodes.txt
      volumes:
      - $patch: delete
        name: beekeeper-test-nodes
