name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Build and test docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create keys
        run: ./create-keys.sh init --nopassword
      - name: Create reg cert
        run: ./create-keys.sh cert untilforever forever
      - name: Build docker images
        run: docker-compose build
      - name: Start docker-compose
        run: docker-compose up -d
      - name: Wait for docker-compose services
        run: while [ $(curl -s localhost:5000)_ != "SAGE Beekeeper API_"  ] ; do echo waiting... ; sleep 2 ; done

      - name: Unit tests
        run: ./unit-tests.sh

      - name: Clean-up
        run: docker-compose down
