name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Build and test docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and run services
        run: make svc-up
      - name: Wait for docker-compose services
        run: while [ $(curl -s localhost:5000)_ != "SAGE Beekeeper API_"  ] ; do echo waiting... ; sleep 2 ; done
      - name: Run tests
        run: make test
      - name: Clean up services
        run: make svc-down
