on:
  release:
    types: [published]
  pull_request:
    branches: ["main"]

jobs:
  push_to_registry_bk-api:
    name: Build Beekeeper API
    uses: waggle-sensor/.github/.github/workflows/build-and-push-docker-image.yml@main
    secrets: inherit
    with:
      context: bk-api
      image: beekeeper-api
  push_to_registry_bk-deploy-manager:
    name: Build Beekeeper Deploy Manager
    uses: waggle-sensor/.github/.github/workflows/build-and-push-docker-image.yml@main
    secrets: inherit
    with:
      context: bk-deploy-manager
      image: beekeeper-deploy-manager
  push_to_registry_bk-sshd:
    name: Build Beekeeper sshd
    uses: waggle-sensor/.github/.github/workflows/build-and-push-docker-image.yml@main
    secrets: inherit
    with:
      context: bk-sshd
      image: beekeeper-sshd
